### ISSUE TITLE
use of `pointer` function causes memory corruption

### ISSUE THREAD

**Issue by vtjnash** [IanButterworth/Darknet.jl#11]
Calling the `pointer` function causes Julia to reuse or clear the underlying memory as soon as possible, as there is no possible way for Julia to track future uses of the pointer. Therefore these are not legal:
https://github.com/IanButterworth/Darknet.jl/blob/d454f0cfd3032b60eb36d93188da979455ccaeae/src/utils.jl#L16
https://github.com/IanButterworth/Darknet.jl/blob/d454f0cfd3032b60eb36d93188da979455ccaeae/src/utils.jl#L18
https://github.com/IanButterworth/Darknet.jl/blob/d454f0cfd3032b60eb36d93188da979455ccaeae/src/utils.jl#L37
https://github.com/IanButterworth/Darknet.jl/blob/d454f0cfd3032b60eb36d93188da979455ccaeae/src/utils.jl#L39

and are the reason this package fails tests sometimes, such as:
https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2021-02/22/Darknet.1.7.0-DEV-10bea8758a.log

Instead, these need to be copied into `Libc.malloc` memory or otherwise teach Darknet.jl to keep track of both the original array and C representation of it.

I suggest defining a Julia-compatible wrapper similar to the following (modulo any typos and such):
```julia
struct Image{N}
    w::Cint
    h::Cint
    c::Cint
    data::Array{Cfloat, N}
end
Base.cconvert(::Type{image}, im::Image) = im
Base.unsafe_convert(::Type{image}, im::Image) = image(im.w, im.h, im.c, pointer(im.data))
```

And changing those statements to `return Image(...)` instead :)

**Comment by IanButterworth** [comment]
Thanks! Sorry for the PkgEval noise. I think if I used this more I would've had to have figured this out sooner.

Much appreciated
